import { pgTable, uuid, integer, text, timestamp, pgEnum } from 'drizzle-orm/pg-core';
import { tenants } from './tenants.schema';
import { users } from './users.schema';
import { products } from './products.schema';
import { sales } from './sales.schema';

export const stockMovementTypeEnum = pgEnum('stock_movement_type', ['entrada', 'saida', 'ajuste']);

export const stockMovements = pgTable('stock_movements', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  productId: uuid('product_id')
    .notNull()
    .references(() => products.id, { onDelete: 'cascade' }),
  type: stockMovementTypeEnum('type').notNull(),
  // Signed delta already applied to the balance (negative on an outbound
  // movement), not the magnitude entered by the user — a direct sum of the
  // ledger reconstructs the balance.
  quantity: integer('quantity').notNull(),
  reason: text('reason'),
  // Filled in only when the movement is automatically generated by a sale.
  saleId: uuid('sale_id').references(() => sales.id, { onDelete: 'set null' }),
  createdBy: uuid('created_by')
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type StockMovementRow = typeof stockMovements.$inferSelect;
export type NewStockMovementRow = typeof stockMovements.$inferInsert;
